[package]
name = "nmcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gltf = "1.4.1"
rmp-serde = "1.3.0"
serde = { version = "1.0.201", features = ["serde_derive"] }
