[package]
name = "mparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msgpacker = { git = "https://github.com/computermouth/msgpacker.git", rev = "9074f28ad3da7ada789aedda67d56808242aeea0" }
